/**
 * Référentiel front Qualiopi — chaque path CRM → indicateurs / preuves / pages liées.
 * Source de vérité pour développer le front « double lecture » métier + Qualiopi.
 * Breadcrumbs = MENU_SIDEBAR ; ce fichier = contenu Qualiopi attendu sur la page.
 *
 * Aligné V9 + Prisma (`docs/QUALIOPI-PRISMA-MAPPING.md`).
 */

import { QUALIOPI_INDICATORS_V9 } from '@/lib/of/qualiopi-indicators';

export type QualiopiPageRole =
  | 'hub' /** landing section / module — agrège, ne produit pas la preuve */
  | 'writer' /** page qui crée / met à jour la preuve métier */
  | 'reader' /** page Qualiopi qui lit / évalue (classeur, passeport, couverture) */
  | 'support' /** support OPS sans indicateur direct (ou indirect faible) */
  | 'na'; /** hors scope Qualiopi typique */

export type QualiopiPageEntry = {
  path: string;
  /** Titre court (sinon repris du menu). */
  title: string;
  role: QualiopiPageRole;
  /** Codes Q-Ixx que cette page doit permettre de satisfaire. */
  indicators: string[];
  /** Ce que Qualiopi / l’auditeur doit pouvoir retrouver ici. */
  mustFind: string[];
  /** Modèles Prisma / Evidence attendus (hints). */
  evidenceHints: string[];
  /** Paths liés (amont / aval / même preuve). */
  relatedPaths: string[];
  /** true = page absente du menu ou à créer. */
  missingInApp?: boolean;
  /** true = pas encore de page.tsx (stub à poser). */
  needsStub?: boolean;
  notes?: string;
};

function indLabel(code: string): string {
  const row = QUALIOPI_INDICATORS_V9.find((i) => i.code === code);
  return row ? `${code} — ${row.label}` : code;
}

/** Lookup public pour UI. */
export function qualiopiIndicatorLabel(code: string): string {
  return indLabel(code);
}

/**
 * Cartographie complète menu CRM + pages Qualiopi métier manquantes.
 * Clé = path canonique (sans hash).
 */
export const QUALIOPI_PAGE_REFERENTIAL: QualiopiPageEntry[] = [
  // ── Accueil ──────────────────────────────────────────────
  {
    path: '/accueil',
    title: 'Accueil CRM',
    role: 'hub',
    indicators: [],
    mustFind: ['Vue agrégée éventuelle des alertes Qualiopi (lien passeport / écarts)'],
    evidenceHints: [],
    relatedPaths: ['/qualiopi', '/qualiopi/referentiel/ecarts'],
    notes: 'Pas de preuve directe — point d’entrée.',
  },

  // ── Qualiopi section ─────────────────────────────────────
  {
    path: '/qualiopi',
    title: 'Qualiopi',
    role: 'hub',
    indicators: [],
    mustFind: ['Cartes modules Référentiel / Pilotage / IA', 'Stats couverture globales'],
    evidenceHints: ['EvidenceIndicatorLink (agrégat)'],
    relatedPaths: [
      '/qualiopi/referentiel',
      '/qualiopi/pilotage',
      '/qualiopi/ia',
      '/qualiopi/referentiel/cartographie-front',
    ],
  },
  {
    path: '/qualiopi/referentiel',
    title: 'Référentiel',
    role: 'hub',
    indicators: [],
    mustFind: ['Accès passeport, classeur, couverture, historique, écarts'],
    evidenceHints: [],
    relatedPaths: [
      '/qualiopi/referentiel/passeport',
      '/qualiopi/referentiel/classeur',
      '/qualiopi/referentiel/couverture',
      '/qualiopi/referentiel/historique',
      '/qualiopi/referentiel/ecarts',
      '/qualiopi/referentiel/cartographie-front',
    ],
  },
  {
    path: '/qualiopi/referentiel/passeport',
    title: 'Passeport session',
    role: 'reader',
    indicators: ['Q-I08', 'Q-I11', 'Q-I30', 'Q-I09', 'Q-I10', 'Q-I12', 'Q-I16'],
    mustFind: [
      'Résultat evaluate session (PASS/FAIL/WARNING/N/A)',
      'Liens actionTarget vers pages métier',
    ],
    evidenceHints: ['API evaluate', 'CandidatureAssessment', 'FormativeAssessment', 'SatisfactionSurvey'],
    relatedPaths: [
      '/gestion-academique/suivi-formations/tableau',
      '/gestion-academique/vie-scolaire/sessions',
      '/qualiopi/referentiel/ecarts',
    ],
  },
  {
    path: '/qualiopi/referentiel/classeur',
    title: 'Classeur',
    role: 'reader',
    indicators: QUALIOPI_INDICATORS_V9.map((i) => i.code),
    mustFind: ['32 cases audit OK/KO/TO_FIX/NA', 'Upload preuve fichier par indicateur'],
    evidenceHints: ['ComplianceDossier SCHOOL_QUALIOPI', 'FileAsset'],
    relatedPaths: ['/qualiopi/referentiel/couverture', '/qualiopi/referentiel/historique'],
  },
  {
    path: '/qualiopi/referentiel/couverture',
    title: 'Couverture',
    role: 'reader',
    indicators: QUALIOPI_INDICATORS_V9.map((i) => i.code),
    mustFind: ['Indicateurs covered via EvidenceIndicatorLink'],
    evidenceHints: ['Evidence', 'EvidenceIndicatorLink'],
    relatedPaths: ['/qualiopi/referentiel/classeur', '/qualiopi/referentiel/passeport'],
  },
  {
    path: '/qualiopi/referentiel/historique',
    title: 'Historique',
    role: 'reader',
    indicators: [],
    mustFind: ['Timeline audits / changements statut classeur'],
    evidenceHints: ['ComplianceItemEvent'],
    relatedPaths: ['/qualiopi/referentiel/classeur'],
  },
  {
    path: '/qualiopi/referentiel/ecarts',
    title: 'Écarts détectés',
    role: 'reader',
    indicators: ['Q-I08', 'Q-I11', 'Q-I20', 'Q-I26', 'Q-I27', 'Q-I30'],
    mustFind: ['Liste FAIL/WARNING moteur Q1', 'Liens correction pages métier'],
    evidenceHints: ['evaluate session/org'],
    relatedPaths: [
      '/gestion-ressources/partenaires/sous-traitants',
      '/gestion-ressources/partenaires/referent-handicap',
      '/gestion-academique/suivi-formations/tableau',
    ],
  },
  {
    path: '/qualiopi/referentiel/cartographie-front',
    title: 'Cartographie front Qualiopi',
    role: 'reader',
    indicators: [],
    mustFind: ['Ce référentiel page → indicateur (outil dev)'],
    evidenceHints: [],
    relatedPaths: ['/qualiopi/referentiel'],
    notes: 'Page outil — pas une preuve audit.',
  },
  {
    path: '/qualiopi/pilotage',
    title: 'Pilotage',
    role: 'hub',
    indicators: ['Q-I02', 'Q-I32'],
    mustFind: ['Alertes OF, indicateurs publiés, rapports'],
    evidenceHints: [],
    relatedPaths: [
      '/qualiopi/pilotage/alertes',
      '/qualiopi/pilotage/indicateurs',
      '/qualiopi/pilotage/rapports',
      '/qualiopi/pilotage/veille',
      '/qualiopi/pilotage/amelioration',
    ],
  },
  {
    path: '/qualiopi/pilotage/alertes',
    title: 'Alertes & écarts OF',
    role: 'reader',
    indicators: ['Q-I31', 'Q-I32'],
    mustFind: ['Alertes score satisfaction, incidents, écarts evaluate'],
    evidenceHints: ['SatisfactionSurvey.scoreAlert', 'QualityIncident'],
    relatedPaths: ['/support-qualite/support/incidents', '/qualiopi/referentiel/ecarts'],
  },
  {
    path: '/qualiopi/pilotage/indicateurs',
    title: 'Indicateurs',
    role: 'writer',
    indicators: ['Q-I02', 'Q-I03'],
    mustFind: ['Publication KPI résultats / taux certification'],
    evidenceHints: ['CertificationOutcomeStat', 'Formation.successRate'],
    relatedPaths: [
      '/gestion-academique/vie-scolaire/formations',
      '/communication-contenu/cms/contenus',
    ],
  },
  {
    path: '/qualiopi/pilotage/rapports',
    title: 'Rapports',
    role: 'reader',
    indicators: ['Q-I02', 'Q-I32'],
    mustFind: ['Exports / synthèses pour audit'],
    evidenceHints: ['CertificationOutcomeStat', 'ContinuousImprovementAction'],
    relatedPaths: ['/qualiopi/pilotage/indicateurs'],
  },
  {
    path: '/qualiopi/pilotage/veille',
    title: 'Veille (légale / métiers / péda)',
    role: 'writer',
    indicators: ['Q-I23', 'Q-I24', 'Q-I25'],
    mustFind: [
      'Items de veille par domaine',
      'Exploitations (prise en compte + diffusion interne)',
    ],
    evidenceHints: ['WatchItem', 'WatchExploitation'],
    relatedPaths: ['/qualiopi/pilotage/amelioration', '/gestion-ressources/compagnie/profil'],
    needsStub: true,
  },
  {
    path: '/qualiopi/pilotage/amelioration',
    title: 'Amélioration continue',
    role: 'writer',
    indicators: ['Q-I32'],
    mustFind: ['Plans d’action issus enquêtes / réclamations / veille'],
    evidenceHints: ['ContinuousImprovementAction'],
    relatedPaths: [
      '/support-qualite/support/tickets',
      '/support-qualite/support/incidents',
      '/gestion-academique/suivi-formations/satisfaction',
      '/qualiopi/pilotage/veille',
    ],
    needsStub: true,
  },
  {
    path: '/qualiopi/ia',
    title: 'IA Qualiopi',
    role: 'hub',
    indicators: [],
    mustFind: ['Brouillons IA à valider (jamais auto-OK)'],
    evidenceHints: [],
    relatedPaths: ['/qualiopi/ia/brouillons', '/qualiopi/ia/historique'],
  },
  {
    path: '/qualiopi/ia/brouillons',
    title: 'Brouillons IA',
    role: 'support',
    indicators: [],
    mustFind: ['Suggestions preuves / textes — validation humaine'],
    evidenceHints: ['AiArtifact'],
    relatedPaths: ['/qualiopi/referentiel/classeur'],
  },
  {
    path: '/qualiopi/ia/historique',
    title: 'Historique IA',
    role: 'support',
    indicators: [],
    mustFind: ['Runs IA passés'],
    evidenceHints: ['AiRun'],
    relatedPaths: ['/qualiopi/ia/brouillons'],
  },

  // ── Gestion ressources ───────────────────────────────────
  {
    path: '/gestion-ressources',
    title: 'Gestion ressources',
    role: 'hub',
    indicators: ['Q-I17', 'Q-I20', 'Q-I21', 'Q-I27'],
    mustFind: ['Cartes modules compagnie / RH / partenaires / moyens'],
    evidenceHints: [],
    relatedPaths: [
      '/gestion-ressources/compagnie',
      '/gestion-ressources/rh',
      '/gestion-ressources/partenaires',
      '/gestion-ressources/equipements',
    ],
  },
  {
    path: '/gestion-ressources/compagnie',
    title: 'Compagnie',
    role: 'hub',
    indicators: ['Q-I01', 'Q-I20'],
    mustFind: ['Profil OF, structure, documents admin'],
    evidenceHints: ['SystemSetting'],
    relatedPaths: [
      '/gestion-ressources/compagnie/profil',
      '/gestion-ressources/compagnie/structure',
      '/gestion-ressources/compagnie/documents',
      '/gestion-ressources/compagnie/conseil-perfectionnement',
    ],
  },
  {
    path: '/gestion-ressources/compagnie/profil',
    title: 'Profil école',
    role: 'writer',
    indicators: ['Q-I01', 'Q-I20'],
    mustFind: [
      'NDA, contacts, site',
      'Référent handicap + mobilité',
      'Infos accessibilité diffusées',
    ],
    evidenceHints: [
      'SystemSetting.disabilityReferent*',
      'SystemSetting.mobilityReferent*',
      'SystemSetting.nda*',
    ],
    relatedPaths: [
      '/gestion-ressources/partenaires/referent-handicap',
      '/communication-contenu/cms/pages-landing',
    ],
  },
  {
    path: '/gestion-ressources/compagnie/structure',
    title: 'Structure',
    role: 'writer',
    indicators: ['Q-I18', 'Q-I20'],
    mustFind: ['Organigramme / unités RH mobilisées pour la prestation'],
    evidenceHints: ['RhOrgUnit', 'RhTeam'],
    relatedPaths: ['/gestion-ressources/rh/equipes'],
  },
  {
    path: '/gestion-ressources/compagnie/documents',
    title: 'Documents compagnie',
    role: 'writer',
    indicators: ['Q-I01', 'Q-I09'],
    mustFind: ['CGV, plaquette, supports contractualisation'],
    evidenceHints: ['FileAsset', 'administrativeDossier'],
    relatedPaths: ['/communication-contenu/cms/contenus'],
  },
  {
    path: '/gestion-ressources/compagnie/conseil-perfectionnement',
    title: 'Conseil de perfectionnement',
    role: 'writer',
    indicators: ['Q-I20'],
    mustFind: ['PV réunions, décisions, participants'],
    evidenceHints: ['PerfectionnementCouncilMeeting'],
    relatedPaths: ['/gestion-ressources/compagnie/profil'],
    needsStub: true,
  },
  {
    path: '/gestion-ressources/rh',
    title: 'Équipe & habilitations',
    role: 'hub',
    indicators: ['Q-I21', 'Q-I22'],
    mustFind: ['Accès collaborateurs / formateurs / équipes'],
    evidenceHints: [],
    relatedPaths: [
      '/gestion-ressources/rh/collaborateurs',
      '/gestion-ressources/rh/formateurs',
      '/gestion-ressources/rh/equipes',
      '/gestion-ressources/rh/absences',
      '/gestion-ressources/rh/competences',
      '/gestion-ressources/rh/developpement',
    ],
  },
  {
    path: '/gestion-ressources/rh/collaborateurs',
    title: 'Collaborateurs',
    role: 'writer',
    indicators: ['Q-I22'],
    mustFind: ['Fiches salariés, dossiers conformité RH'],
    evidenceHints: ['CollaborateurProfile', 'ComplianceDossier'],
    relatedPaths: [
      '/gestion-ressources/rh/developpement',
      '/securite-configuration/acces/users',
    ],
  },
  {
    path: '/gestion-ressources/rh/equipes',
    title: 'Équipes',
    role: 'writer',
    indicators: ['Q-I18'],
    mustFind: ['Composition équipes pédagogiques / session'],
    evidenceHints: ['RhTeam', 'RhTeamMember', 'SessionIntervenantAssignment'],
    relatedPaths: [
      '/gestion-academique/vie-scolaire/sessions',
      '/gestion-ressources/rh/formateurs',
    ],
  },
  {
    path: '/gestion-ressources/rh/formateurs',
    title: 'Formateurs',
    role: 'writer',
    indicators: ['Q-I21'],
    mustFind: ['Compétences, certifications, spécialités intervenants'],
    evidenceHints: ['FormateurProfile', 'TrainerCompetencyReview'],
    relatedPaths: [
      '/gestion-ressources/rh/competences',
      '/gestion-academique/vie-scolaire/sessions',
    ],
  },
  {
    path: '/gestion-ressources/rh/absences',
    title: 'Absences',
    role: 'support',
    indicators: ['Q-I18'],
    mustFind: ['Continuité encadrement (remplacements)'],
    evidenceHints: ['RhAbsence'],
    relatedPaths: ['/gestion-ressources/rh/equipes'],
  },
  {
    path: '/gestion-ressources/rh/competences',
    title: 'Évaluation compétences intervenants',
    role: 'writer',
    indicators: ['Q-I21'],
    mustFind: ['Revues de compétences planifiées / réalisées'],
    evidenceHints: ['TrainerCompetencyReview'],
    relatedPaths: ['/gestion-ressources/rh/formateurs', '/gestion-ressources/rh/developpement'],
    needsStub: true,
  },
  {
    path: '/gestion-ressources/rh/developpement',
    title: 'Développement compétences salariés',
    role: 'writer',
    indicators: ['Q-I22'],
    mustFind: ['Plans formation / actions développement personnel'],
    evidenceHints: ['StaffDevelopmentAction'],
    relatedPaths: ['/gestion-ressources/rh/collaborateurs', '/gestion-ressources/rh/competences'],
    needsStub: true,
  },
  {
    path: '/gestion-ressources/partenaires',
    title: 'Partenaires & accessibilité',
    role: 'hub',
    indicators: ['Q-I20', 'Q-I26', 'Q-I27', 'Q-I28'],
    mustFind: ['Sous-traitants, référent handicap, réseaux'],
    evidenceHints: [],
    relatedPaths: [
      '/gestion-ressources/partenaires/sous-traitants',
      '/gestion-ressources/partenaires/referent-handicap',
      '/gestion-ressources/partenaires/reseau-handicap',
      '/gestion-ressources/partenaires/pfst',
    ],
  },
  {
    path: '/gestion-ressources/partenaires/sous-traitants',
    title: 'Sous-traitants',
    role: 'writer',
    indicators: ['Q-I27'],
    mustFind: ['Qualification ST, contrats, pilotage conformité chaîne qualité'],
    evidenceHints: ['SubcontractorRecord', 'ComplianceDossier SUBCONTRACTOR'],
    relatedPaths: ['/qualiopi/referentiel/ecarts', '/gestion-ressources/rh/formateurs'],
  },
  {
    path: '/gestion-ressources/partenaires/referent-handicap',
    title: 'Référent handicap',
    role: 'writer',
    indicators: ['Q-I20', 'Q-I26'],
    mustFind: ['Nom / contact référent', 'Procédures orientation PSH'],
    evidenceHints: ['SystemSetting.disabilityReferent*', 'DISABILITY_REFERENT dossier'],
    relatedPaths: [
      '/gestion-ressources/partenaires/reseau-handicap',
      '/gestion-ressources/compagnie/profil',
      '/gestion-academique/suivi-formations/tableau',
    ],
  },
  {
    path: '/gestion-ressources/partenaires/reseau-handicap',
    title: 'Réseau / expertises handicap',
    role: 'writer',
    indicators: ['Q-I26'],
    mustFind: ['Partenaires AGEFIPH, MDPH, outils, mobilisations'],
    evidenceHints: ['HandicapNetworkPartner'],
    relatedPaths: ['/gestion-ressources/partenaires/referent-handicap'],
    needsStub: true,
  },
  {
    path: '/gestion-ressources/partenaires/pfst',
    title: 'Partenaires PFST / socio-éco',
    role: 'writer',
    indicators: ['Q-I28'],
    mustFind: ['Accords entreprise d’accueil, co-construction PFST'],
    evidenceHints: ['SocioEconomicPartnership'],
    relatedPaths: ['/gestion-academique/vie-scolaire/sessions'],
    needsStub: true,
    notes: 'required:false — N/A si pas de PFST.',
  },
  {
    path: '/gestion-ressources/equipements',
    title: 'Moyens',
    role: 'hub',
    indicators: ['Q-I17'],
    mustFind: ['Inventaire, salles, maintenance'],
    evidenceHints: ['Equipment', 'FormationVenueRoom'],
    relatedPaths: [
      '/gestion-ressources/equipements/inventaire',
      '/gestion-ressources/equipements/salles',
      '/gestion-ressources/equipements/maintenance',
      '/gestion-ressources/equipements/affectations',
    ],
  },
  {
    path: '/gestion-ressources/equipements/inventaire',
    title: 'Inventaire',
    role: 'writer',
    indicators: ['Q-I17'],
    mustFind: ['Matériel pédagogique / technique adapté'],
    evidenceHints: ['Equipment'],
    relatedPaths: [
      '/gestion-ressources/equipements/affectations',
      '/gestion-academique/vie-scolaire/sessions',
    ],
  },
  {
    path: '/gestion-ressources/equipements/affectations',
    title: 'Affectations',
    role: 'writer',
    indicators: ['Q-I17'],
    mustFind: ['Réservation matériel ↔ session'],
    evidenceHints: ['FormationSession.reservedEquipmentIds'],
    relatedPaths: ['/gestion-academique/vie-scolaire/sessions'],
  },
  {
    path: '/gestion-ressources/equipements/maintenance',
    title: 'Maintenance',
    role: 'writer',
    indicators: ['Q-I17'],
    mustFind: ['État / maintenance équipements'],
    evidenceHints: ['EquipmentMaintenance'],
    relatedPaths: ['/gestion-ressources/equipements/inventaire'],
  },
  {
    path: '/gestion-ressources/equipements/salles',
    title: 'Salles',
    role: 'writer',
    indicators: ['Q-I17'],
    mustFind: ['Locaux adaptés, équipements fixes'],
    evidenceHints: ['FormationVenueRoom', 'VenueRoomFixedEquipment'],
    relatedPaths: ['/gestion-academique/vie-scolaire/sessions'],
  },

  // ── Gestion académique ───────────────────────────────────
  {
    path: '/gestion-academique',
    title: 'Gestion académique',
    role: 'hub',
    indicators: ['Q-I01', 'Q-I04', 'Q-I08', 'Q-I11'],
    mustFind: ['Vie scolaire, LMS, suivi'],
    evidenceHints: [],
    relatedPaths: [
      '/gestion-academique/vie-scolaire',
      '/gestion-academique/lms',
      '/gestion-academique/suivi-formations',
    ],
  },
  {
    path: '/gestion-academique/vie-scolaire',
    title: 'Vie scolaire',
    role: 'hub',
    indicators: ['Q-I01', 'Q-I05', 'Q-I06', 'Q-I09'],
    mustFind: ['Formations, sessions, planning, étudiants'],
    evidenceHints: [],
    relatedPaths: [
      '/gestion-academique/vie-scolaire/formations',
      '/gestion-academique/vie-scolaire/sessions',
      '/gestion-academique/vie-scolaire/planning',
      '/gestion-academique/vie-scolaire/etudiants',
    ],
  },
  {
    path: '/gestion-academique/vie-scolaire/formations',
    title: 'Formations',
    role: 'writer',
    indicators: ['Q-I01', 'Q-I02', 'Q-I03', 'Q-I05', 'Q-I06', 'Q-I07'],
    mustFind: [
      'Info publique : prérequis, objectifs, délais, méthodes, évaluation, accessibilité',
      'Objectifs opérationnels, contenus, adéquation RNCP',
    ],
    evidenceHints: [
      'Formation.public*',
      'Formation.operationalObjectivesSummary',
      'Formation.rncp*',
      'CertificationOutcomeStat',
    ],
    relatedPaths: [
      '/communication-contenu/cms/contenus',
      '/qualiopi/pilotage/indicateurs',
      '/gestion-academique/vie-scolaire/sessions',
    ],
  },
  {
    path: '/gestion-academique/vie-scolaire/sessions',
    title: 'Sessions',
    role: 'writer',
    indicators: [
      'Q-I09',
      'Q-I10',
      'Q-I12',
      'Q-I16',
      'Q-I17',
      'Q-I18',
      'Q-I19',
    ],
    mustFind: [
      'Conditions déroulement, salle, formateur, matériel',
      'Coordination intervenants, ressources péda',
      'Checklist présentation certification',
    ],
    evidenceHints: [
      'FormationSession',
      'FormationSessionConvention',
      'SessionIntervenantAssignment',
      'PedagogicalResourceDelivery',
      'SessionCertificationPresentation',
    ],
    relatedPaths: [
      '/gestion-academique/suivi-formations/tableau',
      '/qualiopi/referentiel/passeport',
      '/gestion-ressources/equipements/salles',
      '/gestion-ressources/rh/formateurs',
    ],
  },
  {
    path: '/gestion-academique/vie-scolaire/planning',
    title: 'Planning',
    role: 'writer',
    indicators: ['Q-I09', 'Q-I18'],
    mustFind: ['Calendrier sessions / créneaux communiqués'],
    evidenceHints: ['FormationSessionDay', 'VenueRoomBooking'],
    relatedPaths: ['/gestion-academique/vie-scolaire/sessions'],
  },
  {
    path: '/gestion-academique/vie-scolaire/etudiants',
    title: 'Étudiants',
    role: 'writer',
    indicators: ['Q-I04', 'Q-I08', 'Q-I10', 'Q-I12'],
    mustFind: [
      'Dossiers bénéficiaires, analyse besoin, positionnement, adaptations',
      'Risque rupture / engagement',
    ],
    evidenceHints: [
      'Candidature',
      'CandidatureAssessment',
      'EngagementMeasure',
      'dropoutRisk*',
    ],
    relatedPaths: [
      '/gestion-academique/suivi-formations/tableau',
      '/administration-facturation/financeurs/dossiers',
      '/gestion-academique/vie-scolaire/alternance',
      '/gestion-academique/vie-scolaire/insertion',
    ],
  },
  {
    path: '/gestion-academique/vie-scolaire/alternance',
    title: 'Alternance (tuteurs / missions)',
    role: 'writer',
    indicators: ['Q-I13', 'Q-I14', 'Q-I15'],
    mustFind: [
      'Lien tuteur entreprise',
      'Missions court/moyen/long terme',
      'Ack droits/devoirs apprentis',
      'Accompagnement socio-pro',
    ],
    evidenceHints: [
      'CompanyTutorLink',
      'ApprenticeshipMission',
      'ApprenticeRightsAck',
      'SocioProfessionalSupportAction',
    ],
    relatedPaths: [
      '/gestion-academique/vie-scolaire/etudiants',
      '/gestion-ressources/partenaires/pfst',
    ],
    needsStub: true,
    notes: 'required:false — N/A hors CFA/alternance.',
  },
  {
    path: '/gestion-academique/vie-scolaire/insertion',
    title: 'Suivi insertion / poursuite d’études',
    role: 'writer',
    indicators: ['Q-I29'],
    mustFind: ['Suivis post-formation (emploi / études)'],
    evidenceHints: ['InsertionFollowUp'],
    relatedPaths: ['/gestion-academique/vie-scolaire/etudiants'],
    needsStub: true,
    notes: 'required:false selon offre.',
  },
  {
    path: '/gestion-academique/lms',
    title: 'LMS',
    role: 'hub',
    indicators: ['Q-I11', 'Q-I19'],
    mustFind: ['Cours, devoirs, discussions, inscriptions LMS'],
    evidenceHints: ['Course', 'Chapter', 'Attachment'],
    relatedPaths: [
      '/gestion-academique/lms/cours',
      '/gestion-academique/lms/devoirs',
      '/gestion-academique/lms/discussions',
      '/gestion-academique/lms/inscriptions',
    ],
  },
  {
    path: '/gestion-academique/lms/cours',
    title: 'Cours LMS',
    role: 'writer',
    indicators: ['Q-I06', 'Q-I19'],
    mustFind: ['Ressources pédagogiques numériques mises à disposition'],
    evidenceHints: ['Course', 'Chapter', 'PedagogicalResourceDelivery'],
    relatedPaths: ['/gestion-academique/vie-scolaire/sessions'],
  },
  {
    path: '/gestion-academique/lms/devoirs',
    title: 'Devoirs LMS',
    role: 'writer',
    indicators: ['Q-I11'],
    mustFind: ['Évaluations / remises (complément formative présentiel)'],
    evidenceHints: ['Assignment', 'AssignmentSubmission'],
    relatedPaths: ['/gestion-academique/suivi-formations/tableau'],
  },
  {
    path: '/gestion-academique/lms/discussions',
    title: 'Discussions LMS',
    role: 'support',
    indicators: ['Q-I12'],
    mustFind: ['Engagement pédagogique (preuve faible)'],
    evidenceHints: ['Discussion'],
    relatedPaths: ['/gestion-academique/lms/cours'],
  },
  {
    path: '/gestion-academique/lms/inscriptions',
    title: 'Inscriptions LMS',
    role: 'writer',
    indicators: ['Q-I09', 'Q-I19'],
    mustFind: ['Accès bénéficiaire aux ressources'],
    evidenceHints: ['Enrollment'],
    relatedPaths: ['/gestion-academique/vie-scolaire/etudiants'],
  },
  {
    path: '/gestion-academique/suivi-formations',
    title: 'Suivi formations',
    role: 'hub',
    indicators: ['Q-I08', 'Q-I11', 'Q-I30'],
    mustFind: ['Tableau session, satisfaction, circuits'],
    evidenceHints: [],
    relatedPaths: [
      '/gestion-academique/suivi-formations/tableau',
      '/gestion-academique/suivi-formations/satisfaction',
      '/gestion-academique/suivi-formations/circuits',
    ],
  },
  {
    path: '/gestion-academique/suivi-formations/tableau',
    title: 'Tableau de suivi',
    role: 'writer',
    indicators: [
      'Q-I08',
      'Q-I10',
      'Q-I11',
      'Q-I12',
      'Q-I16',
      'Q-I30',
    ],
    mustFind: [
      'Positionnement, formatives, émargements, adaptations',
      'Prévention ruptures, examens',
      'Lien passeport Qualiopi',
    ],
    evidenceHints: [
      'CandidatureAssessment',
      'FormativeAssessment',
      'FormationSessionEmargement',
      'EngagementMeasure',
      'FormationExam',
    ],
    relatedPaths: [
      '/qualiopi/referentiel/passeport',
      '/gestion-academique/vie-scolaire/sessions',
      '/gestion-academique/suivi-formations/satisfaction',
    ],
  },
  {
    path: '/gestion-academique/suivi-formations/satisfaction',
    title: 'Satisfaction',
    role: 'writer',
    indicators: ['Q-I30', 'Q-I32'],
    mustFind: [
      'Enquêtes HOT/COLD/COMPANY/TRAINER/FUNDER',
      'Alertes score → amélioration',
    ],
    evidenceHints: ['SatisfactionSurvey'],
    relatedPaths: [
      '/qualiopi/pilotage/amelioration',
      '/support-qualite/support/tickets',
      '/gestion-academique/suivi-formations/tableau',
    ],
  },
  {
    path: '/gestion-academique/suivi-formations/circuits',
    title: 'Circuits',
    role: 'support',
    indicators: ['Q-I18'],
    mustFind: ['Orchestration jalons (n8n) — coordination, pas preuve seule'],
    evidenceHints: ['SessionAutomationRun'],
    relatedPaths: ['/gestion-academique/vie-scolaire/sessions'],
  },

  // ── Finance ──────────────────────────────────────────────
  {
    path: '/administration-facturation',
    title: 'Finance',
    role: 'hub',
    indicators: ['Q-I04'],
    mustFind: ['Devis, financeurs, budget'],
    evidenceHints: [],
    relatedPaths: [
      '/administration-facturation/finance',
      '/administration-facturation/financeurs',
      '/administration-facturation/budget',
    ],
  },
  {
    path: '/administration-facturation/finance',
    title: 'Devis & facturation',
    role: 'hub',
    indicators: ['Q-I01', 'Q-I04'],
    mustFind: ['Supports contractualisation / tarifs'],
    evidenceHints: ['FinanceDevis'],
    relatedPaths: [
      '/administration-facturation/finance/devis',
      '/administration-facturation/finance/factures',
      '/administration-facturation/finance/paiements',
    ],
  },
  {
    path: '/administration-facturation/finance/devis',
    title: 'Devis',
    role: 'writer',
    indicators: ['Q-I01', 'Q-I04'],
    mustFind: ['Proposition commerciale = info publique + besoin'],
    evidenceHints: ['FinanceDevis', 'TrainingRequest'],
    relatedPaths: [
      '/gestion-academique/vie-scolaire/formations',
      '/communication-contenu/cms/contenus',
    ],
  },
  {
    path: '/administration-facturation/finance/factures',
    title: 'Factures',
    role: 'support',
    indicators: [],
    mustFind: ['Preuve faible Qualiopi (finance interne)'],
    evidenceHints: ['FinanceInvoice'],
    relatedPaths: ['/administration-facturation/finance/devis'],
  },
  {
    path: '/administration-facturation/finance/paiements',
    title: 'Paiements',
    role: 'support',
    indicators: [],
    mustFind: ['Hors indicateurs RNQ directs'],
    evidenceHints: [],
    relatedPaths: ['/administration-facturation/finance/factures'],
  },
  {
    path: '/administration-facturation/financeurs',
    title: 'Financeurs',
    role: 'hub',
    indicators: ['Q-I04', 'Q-I30'],
    mustFind: ['Dossiers financeur, appréciations financeur'],
    evidenceHints: ['FundingCase'],
    relatedPaths: [
      '/administration-facturation/financeurs/dossiers',
      '/administration-facturation/financeurs/edof-catalog',
    ],
  },
  {
    path: '/administration-facturation/financeurs/dossiers',
    title: 'Dossiers financeurs',
    role: 'writer',
    indicators: ['Q-I04'],
    mustFind: ['Lien besoin bénéficiaire ↔ financeur'],
    evidenceHints: ['FundingCase', 'CandidatureAssessment NEEDS_ANALYSIS'],
    relatedPaths: ['/gestion-academique/vie-scolaire/etudiants'],
  },
  {
    path: '/administration-facturation/financeurs/edof-catalog',
    title: 'Export EDOF',
    role: 'writer',
    indicators: ['Q-I01', 'Q-I02'],
    mustFind: ['Cohérence catalogue diffusé (info publique / KPI)'],
    evidenceHints: ['FormationCatalogOffer'],
    relatedPaths: ['/communication-contenu/cms/contenus'],
  },
  {
    path: '/administration-facturation/budget',
    title: 'Budget & pilotage',
    role: 'hub',
    indicators: [],
    mustFind: ['BPF / budget — lien Qualiopi indirect'],
    evidenceHints: [],
    relatedPaths: [
      '/administration-facturation/budget/lignes',
      '/administration-facturation/budget/bpf',
      '/administration-facturation/budget/rapports',
    ],
  },
  {
    path: '/administration-facturation/budget/lignes',
    title: 'Budget',
    role: 'na',
    indicators: [],
    mustFind: [],
    evidenceHints: [],
    relatedPaths: [],
    notes: 'Hors RNQ Qualiopi.',
  },
  {
    path: '/administration-facturation/budget/bpf',
    title: 'BPF',
    role: 'support',
    indicators: ['Q-I02'],
    mustFind: ['Données activité / bilans (preuve statistique possible)'],
    evidenceHints: ['CertificationOutcomeStat'],
    relatedPaths: ['/qualiopi/pilotage/indicateurs'],
  },
  {
    path: '/administration-facturation/budget/rapports',
    title: 'Rapports finance',
    role: 'na',
    indicators: [],
    mustFind: [],
    evidenceHints: [],
    relatedPaths: [],
  },

  // ── Vitrine & acquisition ────────────────────────────────
  {
    path: '/communication-contenu',
    title: 'Vitrine & acquisition',
    role: 'hub',
    indicators: ['Q-I01', 'Q-I02'],
    mustFind: ['Diffusion info publique'],
    evidenceHints: [],
    relatedPaths: [
      '/communication-contenu/cms',
      '/communication-contenu/marketing',
      '/communication-contenu/seo',
    ],
  },
  {
    path: '/communication-contenu/cms',
    title: 'CMS',
    role: 'hub',
    indicators: ['Q-I01'],
    mustFind: ['Landing, équipe, catalogue'],
    evidenceHints: [],
    relatedPaths: [
      '/communication-contenu/cms/pages-landing',
      '/communication-contenu/cms/equipe-landing',
      '/communication-contenu/cms/contenus',
    ],
  },
  {
    path: '/communication-contenu/cms/pages-landing',
    title: 'Pages landing',
    role: 'writer',
    indicators: ['Q-I01'],
    mustFind: ['Info accessible : objectifs, délais, tarifs, accessibilité PSH'],
    evidenceHints: ['LandingConfig', 'Formation public fields'],
    relatedPaths: [
      '/gestion-academique/vie-scolaire/formations',
      '/gestion-ressources/compagnie/profil',
    ],
  },
  {
    path: '/communication-contenu/cms/equipe-landing',
    title: 'Équipe landing',
    role: 'writer',
    indicators: ['Q-I01', 'Q-I21'],
    mustFind: ['Présentation intervenants (crédibilité / compétences)'],
    evidenceHints: ['LandingTeamOffer', 'FormateurProfile'],
    relatedPaths: ['/gestion-ressources/rh/formateurs'],
  },
  {
    path: '/communication-contenu/cms/contenus',
    title: 'Catalogue vitrine',
    role: 'writer',
    indicators: ['Q-I01', 'Q-I02', 'Q-I03'],
    mustFind: ['Fiches formation publiques + KPI / RNCP'],
    evidenceHints: ['Formation', 'FormationCatalogOffer', 'CertificationOutcomeStat'],
    relatedPaths: [
      '/gestion-academique/vie-scolaire/formations',
      '/qualiopi/pilotage/indicateurs',
    ],
  },
  {
    path: '/communication-contenu/marketing',
    title: 'Marketing',
    role: 'hub',
    indicators: ['Q-I01', 'Q-I04'],
    mustFind: ['Leads / campagnes = entrée analyse besoin'],
    evidenceHints: ['Lead'],
    relatedPaths: [
      '/communication-contenu/marketing/formulaires-leads',
      '/communication-contenu/marketing/campagnes',
    ],
  },
  {
    path: '/communication-contenu/marketing/formulaires-leads',
    title: 'Formulaires leads',
    role: 'writer',
    indicators: ['Q-I04'],
    mustFind: ['Capture besoin amont (pré-analyse)'],
    evidenceHints: ['Lead', 'Candidature'],
    relatedPaths: ['/gestion-academique/vie-scolaire/etudiants'],
  },
  {
    path: '/communication-contenu/marketing/campagnes',
    title: 'Campagnes',
    role: 'support',
    indicators: ['Q-I01'],
    mustFind: ['Supports pub = canal info publique'],
    evidenceHints: ['MarketingCampaign'],
    relatedPaths: ['/communication-contenu/cms/pages-landing'],
  },
  {
    path: '/communication-contenu/seo',
    title: 'SEO',
    role: 'hub',
    indicators: ['Q-I01'],
    mustFind: ['Accessibilité info (indexation)'],
    evidenceHints: [],
    relatedPaths: [
      '/communication-contenu/seo/meta-indexation',
      '/communication-contenu/seo/redirections',
    ],
  },
  {
    path: '/communication-contenu/seo/meta-indexation',
    title: 'Meta indexation',
    role: 'support',
    indicators: ['Q-I01'],
    mustFind: ['Visibilité info publique'],
    evidenceHints: [],
    relatedPaths: ['/communication-contenu/cms/contenus'],
  },
  {
    path: '/communication-contenu/seo/redirections',
    title: 'Redirections',
    role: 'na',
    indicators: [],
    mustFind: [],
    evidenceHints: [],
    relatedPaths: [],
  },

  // ── Support ──────────────────────────────────────────────
  {
    path: '/support-qualite',
    title: 'Support',
    role: 'hub',
    indicators: ['Q-I31', 'Q-I32'],
    mustFind: ['Tickets / incidents = réclamations'],
    evidenceHints: [],
    relatedPaths: ['/support-qualite/support'],
  },
  {
    path: '/support-qualite/support',
    title: 'Support',
    role: 'hub',
    indicators: ['Q-I31'],
    mustFind: ['Tickets et incidents qualité'],
    evidenceHints: [],
    relatedPaths: [
      '/support-qualite/support/tickets',
      '/support-qualite/support/incidents',
    ],
  },
  {
    path: '/support-qualite/support/tickets',
    title: 'Tickets',
    role: 'writer',
    indicators: ['Q-I31', 'Q-I32'],
    mustFind: [
      'Réclamations parties prenantes (isComplaint)',
      'Ack / 1ère réponse',
      'Lien amélioration continue',
    ],
    evidenceHints: ['SupportTicket.isComplaint', 'ContinuousImprovementAction'],
    relatedPaths: [
      '/support-qualite/support/incidents',
      '/qualiopi/pilotage/amelioration',
      '/gestion-academique/suivi-formations/satisfaction',
    ],
  },
  {
    path: '/support-qualite/support/incidents',
    title: 'Incidents',
    role: 'writer',
    indicators: ['Q-I31', 'Q-I32'],
    mustFind: ['Difficultés / aléas, cause racine, action corrective'],
    evidenceHints: ['QualityIncident', 'ContinuousImprovementAction'],
    relatedPaths: [
      '/support-qualite/support/tickets',
      '/qualiopi/pilotage/amelioration',
    ],
  },

  // ── Sécurité ─────────────────────────────────────────────
  {
    path: '/securite-configuration',
    title: 'Sécurité configuration',
    role: 'hub',
    indicators: [],
    mustFind: ['Accès, paramètres, gouvernance — support OF'],
    evidenceHints: [],
    relatedPaths: [
      '/securite-configuration/acces',
      '/securite-configuration/parametres',
      '/securite-configuration/gouvernance-donnees',
    ],
  },
  {
    path: '/securite-configuration/acces',
    title: 'Accès',
    role: 'hub',
    indicators: [],
    mustFind: [],
    evidenceHints: [],
    relatedPaths: [
      '/securite-configuration/acces/users',
      '/securite-configuration/acces/roles',
      '/securite-configuration/acces/permissions',
      '/securite-configuration/acces/logs',
    ],
  },
  {
    path: '/securite-configuration/acces/users',
    title: 'Utilisateurs',
    role: 'support',
    indicators: ['Q-I21'],
    mustFind: ['Comptes intervenants (habilitation)'],
    evidenceHints: ['User', 'FormateurProfile'],
    relatedPaths: ['/gestion-ressources/rh/collaborateurs'],
  },
  {
    path: '/securite-configuration/acces/roles',
    title: 'Rôles',
    role: 'na',
    indicators: [],
    mustFind: [],
    evidenceHints: [],
    relatedPaths: [],
  },
  {
    path: '/securite-configuration/acces/permissions',
    title: 'Permissions',
    role: 'na',
    indicators: [],
    mustFind: [],
    evidenceHints: [],
    relatedPaths: [],
  },
  {
    path: '/securite-configuration/acces/logs',
    title: 'Logs',
    role: 'support',
    indicators: [],
    mustFind: ['Traçabilité (preuve secondaire)'],
    evidenceHints: ['SystemLog'],
    relatedPaths: [],
  },
  {
    path: '/securite-configuration/parametres',
    title: 'Paramètres',
    role: 'hub',
    indicators: ['Q-I20'],
    mustFind: ['Settings système incl. référents'],
    evidenceHints: ['SystemSetting'],
    relatedPaths: [
      '/securite-configuration/parametres/settings',
      '/securite-configuration/parametres/sante-systeme',
      '/gestion-ressources/compagnie/profil',
    ],
  },
  {
    path: '/securite-configuration/parametres/settings',
    title: 'Paramètres système',
    role: 'writer',
    indicators: ['Q-I01', 'Q-I20'],
    mustFind: ['Identité OF, contacts, référents handicap/mobilité'],
    evidenceHints: ['SystemSetting'],
    relatedPaths: ['/gestion-ressources/compagnie/profil'],
  },
  {
    path: '/securite-configuration/parametres/sante-systeme',
    title: 'Santé système',
    role: 'na',
    indicators: [],
    mustFind: [],
    evidenceHints: [],
    relatedPaths: [],
  },
  {
    path: '/securite-configuration/gouvernance-donnees',
    title: 'Gouvernance données',
    role: 'hub',
    indicators: [],
    mustFind: ['Preuves documentaires / conservation'],
    evidenceHints: ['FileAsset'],
    relatedPaths: [
      '/securite-configuration/gouvernance-donnees/conformite',
      '/securite-configuration/gouvernance-donnees/storage',
      '/securite-configuration/gouvernance-donnees/demandes-documents',
      '/securite-configuration/gouvernance-donnees/corbeille-archivage',
      '/securite-configuration/gouvernance-donnees/audit-documentaire',
    ],
  },
  {
    path: '/securite-configuration/gouvernance-donnees/conformite',
    title: 'Conformité RGPD',
    role: 'support',
    indicators: [],
    mustFind: ['Cadre légal données (pas RNQ direct)'],
    evidenceHints: [],
    relatedPaths: [],
  },
  {
    path: '/securite-configuration/gouvernance-donnees/storage',
    title: 'Storage',
    role: 'support',
    indicators: [],
    mustFind: ['Conservation preuves fichiers'],
    evidenceHints: ['FileAsset'],
    relatedPaths: ['/qualiopi/referentiel/classeur'],
  },
  {
    path: '/securite-configuration/gouvernance-donnees/demandes-documents',
    title: 'Demandes documents',
    role: 'writer',
    indicators: ['Q-I09', 'Q-I10'],
    mustFind: ['Collecte pièces bénéficiaires'],
    evidenceHints: ['DocumentRequest', 'ComplianceDossier'],
    relatedPaths: ['/gestion-academique/vie-scolaire/etudiants'],
  },
  {
    path: '/securite-configuration/gouvernance-donnees/corbeille-archivage',
    title: 'Corbeille archivage',
    role: 'support',
    indicators: [],
    mustFind: ['Rétention preuves'],
    evidenceHints: ['FileAsset.archivedAt'],
    relatedPaths: [],
  },
  {
    path: '/securite-configuration/gouvernance-donnees/audit-documentaire',
    title: 'Audit documentaire',
    role: 'reader',
    indicators: [],
    mustFind: ['Traçabilité pièces (soutien classeur)'],
    evidenceHints: ['ComplianceItemEvent'],
    relatedPaths: ['/qualiopi/referentiel/classeur'],
  },
];

export function getQualiopiPageEntry(path: string): QualiopiPageEntry | undefined {
  const normalized = path.replace(/\/$/, '') || '/';
  return QUALIOPI_PAGE_REFERENTIAL.find((e) => e.path === normalized);
}

export function listMissingQualiopiPages(): QualiopiPageEntry[] {
  return QUALIOPI_PAGE_REFERENTIAL.filter((e) => e.missingInApp || e.needsStub);
}

export function listPagesForIndicator(code: string): QualiopiPageEntry[] {
  return QUALIOPI_PAGE_REFERENTIAL.filter((e) => e.indicators.includes(code));
}

export function listWriterPages(): QualiopiPageEntry[] {
  return QUALIOPI_PAGE_REFERENTIAL.filter((e) => e.role === 'writer');
}
