import { z } from 'zod';
import {
  rhContactFields,
  zContractType,
  zUserCategory,
  zUserStatusEdit,
  zWorkTimeType,
} from '@/lib/rh-form-schema-shared';

export const ConformiteEditSchema = z.object({
  firstName: z.string().min(1, { message: 'Le prénom est requis.' }).min(2),
  lastName: z.string().min(1, { message: 'Le nom est requis.' }).min(2),
  email: z.string().email({ message: 'Email invalide.' }),
  ...rhContactFields,
  roleId: z.string().min(1, { message: 'Le rôle est requis.' }),
  userCategory: zUserCategory,
  jobFunction: z.string().optional(),
  jobPositionId: z.string().optional().nullable(),
  qualification: z.string().optional(),
  status: zUserStatusEdit,
  birthDate: z.string().optional(),
  birthPlace: z.string().optional(),
  nationality: z.string().optional(),
  socialSecurityNumber: z.string().optional(),
  cniNumber: z.string().optional(),
  residencePermitNumber: z.string().optional(),
  residencePermitExpiry: z.string().optional(),
  carteProNumber: z.string().optional(),
  carteProExpiry: z.string().optional(),
  isSchedulable: z.boolean(),
  contractType: zContractType,
  workTimeType: zWorkTimeType,
  contractStartDate: z.string().optional(),
  contractEndDate: z.string().optional(),
  address: z.string().optional(),
  city: z.string().optional(),
  postalCode: z.string().optional(),
  avatarFile: z.any().optional(),
  avatarAction: z.enum(['save', 'remove', '']).optional(),
  documentCni: z.any().optional(),
  documentAssurance: z.any().optional(),
  documentResidencePermit: z.any().optional(),
  documentCartePro: z.any().optional(),
});

export type ConformiteEditSchemaType = z.infer<typeof ConformiteEditSchema>;
