# Copie statique si HTTPS desactive (etape prepare HTTP)
api:
  dashboard: false

entryPoints:
  web:
    address: ":80"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: INFO
