import type { DocTypeDefinition } from '@repo/doctype';
import { CRM_PERMISSION } from '@/lib/auth/crm-permissions';

export const companyDocType: DocTypeDefinition = {
  name: 'Company',
  module: 'crm',
  label: 'Société',
  table: 'Company',
  schemaVersion: 1,
  aliases: ['company'],
  fields: [
    { fieldname: 'name', label: 'Raison sociale', fieldtype: 'Data', required: true, searchable: true },
    { fieldname: 'siret', label: 'SIRET', fieldtype: 'Data', searchable: true },
    { fieldname: 'kind', label: 'Type', fieldtype: 'Select', required: true },
    { fieldname: 'email', label: 'E-mail', fieldtype: 'Email', searchable: true },
    { fieldname: 'phone', label: 'Téléphone', fieldtype: 'Phone' },
    { fieldname: 'address', label: 'Adresse', fieldtype: 'Text' },
    { fieldname: 'isActive', label: 'Active', fieldtype: 'Boolean' },
    { fieldname: 'notes', label: 'Notes', fieldtype: 'Text' },
  ],
  permissions: [
    {
      role: '*',
      permlevel: 0,
      read: true,
      requires: { anyPermissionSlugs: [CRM_PERMISSION.communicationView] },
    },
    {
      role: '*',
      permlevel: 0,
      create: true,
      write: true,
      delete: true,
      requires: { anyPermissionSlugs: [CRM_PERMISSION.communicationEdit] },
    },
  ],
  naming: { strategy: 'UUID_INTERNAL' },
  flags: { isChild: false, isSingle: false, isVirtual: false, isSubmittable: false },
  list: {
    searchFields: ['name', 'siret', 'email'],
    defaultSort: { fieldname: 'name', direction: 'asc' },
    pageSize: 25,
  },
  persistence: {
    table: 'Company',
    delegate: 'company',
    nameField: 'id',
    creationField: 'createdAt',
    modifiedField: 'updatedAt',
  },
};

export const contactDocType: DocTypeDefinition = {
  name: 'Contact',
  module: 'crm',
  label: 'Contact',
  table: 'Contact',
  schemaVersion: 1,
  aliases: ['contact'],
  fields: [
    { fieldname: 'firstName', label: 'Prénom', fieldtype: 'Data', required: true, searchable: true },
    { fieldname: 'lastName', label: 'Nom', fieldtype: 'Data', required: true, searchable: true },
    { fieldname: 'email', label: 'E-mail', fieldtype: 'Email', searchable: true },
    { fieldname: 'phone', label: 'Téléphone', fieldtype: 'Phone' },
    { fieldname: 'jobTitle', label: 'Fonction', fieldtype: 'Data' },
    {
      fieldname: 'companyId',
      label: 'Société',
      fieldtype: 'Link',
      options: 'Company',
      linkDisplayField: 'name',
    },
    {
      fieldname: 'leadId',
      label: 'Lead',
      fieldtype: 'Link',
      options: 'Lead',
      linkDisplayField: 'email',
    },
    { fieldname: 'notes', label: 'Notes', fieldtype: 'Text' },
  ],
  permissions: [
    {
      role: '*',
      permlevel: 0,
      read: true,
      requires: { anyPermissionSlugs: [CRM_PERMISSION.communicationView] },
    },
    {
      role: '*',
      permlevel: 0,
      create: true,
      write: true,
      delete: true,
      requires: { anyPermissionSlugs: [CRM_PERMISSION.communicationEdit] },
    },
  ],
  naming: { strategy: 'UUID_INTERNAL' },
  flags: { isChild: false, isSingle: false, isVirtual: false, isSubmittable: false },
  list: {
    searchFields: ['firstName', 'lastName', 'email', 'phone'],
    defaultSort: { fieldname: 'lastName', direction: 'asc' },
    pageSize: 25,
  },
  persistence: {
    table: 'Contact',
    delegate: 'contact',
    nameField: 'id',
    creationField: 'createdAt',
    modifiedField: 'updatedAt',
  },
};

export const trainingRequestDocType: DocTypeDefinition = {
  name: 'TrainingRequest',
  module: 'crm',
  label: 'Demande de formation',
  table: 'TrainingRequest',
  schemaVersion: 1,
  aliases: ['trainingRequest'],
  fields: [
    { fieldname: 'reference', label: 'Référence', fieldtype: 'Data', unique: true, searchable: true },
    {
      fieldname: 'companyId',
      label: 'Société',
      fieldtype: 'Link',
      options: 'Company',
      linkDisplayField: 'name',
    },
    {
      fieldname: 'contactId',
      label: 'Contact',
      fieldtype: 'Link',
      options: 'Contact',
      linkDisplayField: 'lastName',
    },
    {
      fieldname: 'formationId',
      label: 'Formation',
      fieldtype: 'Link',
      options: 'Formation',
      linkDisplayField: 'name',
    },
    { fieldname: 'status', label: 'Statut', fieldtype: 'Select', required: true },
    { fieldname: 'headcount', label: 'Effectif', fieldtype: 'Integer' },
    { fieldname: 'notes', label: 'Notes', fieldtype: 'Text' },
    {
      fieldname: 'ownerUserId',
      label: 'Owner',
      fieldtype: 'Link',
      options: 'User',
      linkDisplayField: 'name',
    },
  ],
  permissions: [
    {
      role: '*',
      permlevel: 0,
      read: true,
      requires: { anyPermissionSlugs: [CRM_PERMISSION.communicationView] },
    },
    {
      role: '*',
      permlevel: 0,
      create: true,
      write: true,
      delete: true,
      requires: { anyPermissionSlugs: [CRM_PERMISSION.communicationEdit] },
    },
  ],
  naming: { strategy: 'UUID_INTERNAL' },
  flags: { isChild: false, isSingle: false, isVirtual: false, isSubmittable: false },
  list: {
    searchFields: ['reference'],
    defaultSort: { fieldname: 'createdAt', direction: 'desc' },
    pageSize: 25,
  },
  persistence: {
    table: 'TrainingRequest',
    delegate: 'trainingRequest',
    nameField: 'id',
    ownerField: 'ownerUserId',
    creationField: 'createdAt',
    modifiedField: 'updatedAt',
  },
};
