---
- Liens rapides:
    - App:
        - abbr: APP
          href: https://hosting-global-it-ss.com
    - CRM:
        - abbr: CRM
          href: https://crm.hosting-global-it-ss.com
    - n8n:
        - abbr: n8n
          href: https://n8n-k2pw.srv1722028.hstgr.cloud
