---
- Ressources VPS:
    label: Serveur 187.77.166.124
    cpu: true
    memory: true
    disk: /
    uptime: true
    expanded: true

- datetime:
    text_size: md
    locale: fr
    format:
      dateStyle: medium
      timeStyle: short
      hourCycle: h23
