@echo off
cd /d "c:\laragon\www\lms\apps\lms-crm\app\(protected)\gestion-academique\admissions\candidats\components"
ren "collaborateur-access-details.tsx" "candidat-access-details.tsx"
ren "collaborateur-access-stats.tsx" "candidat-access-stats.tsx"
ren "collaborateur-hr-info.tsx" "candidat-info.tsx"
ren "collaborateur-overview-stats.tsx" "candidat-overview-stats.tsx"
ren "collaborateur-permissions-list.tsx" "candidat-permissions-list.tsx"
ren "collaborateur-recent-activity.tsx" "candidat-recent-activity.tsx"
ren "collaborateur-reliability-tier.tsx" "candidat-reliability-tier.tsx"
ren "collaborateur-roles-groups.tsx" "candidat-roles-groups.tsx"

cd /d "c:\laragon\www\lms\apps\lms-crm\app\(protected)\gestion-academique\admissions\candidats\components"
ren "collaborateur-add-dialog.tsx" "candidat-add-dialog.tsx"
ren "collaborateur-add-sheet.tsx" "candidat-add-sheet.tsx"
ren "collaborateur-details-absences.tsx" "candidat-details-absences.tsx"
ren "collaborateur-details-activity.tsx" "candidat-details-activity.tsx"
ren "collaborateur-details-compliance.tsx" "candidat-details-compliance.tsx"
ren "collaborateur-details-documents.tsx" "candidat-details-documents.tsx"
ren "collaborateur-details-overview.tsx" "candidat-details-overview.tsx"
ren "collaborateur-details-permissions.tsx" "candidat-details-permissions.tsx"
ren "collaborateur-details-settings.tsx" "candidat-details-settings.tsx"
ren "collaborateur-details-sheet.tsx" "candidat-details-sheet.tsx"
ren "collaborateur-list.tsx" "candidat-list.tsx"
ren "collaborateur-stats.tsx" "candidat-stats.tsx"

cd /d "c:\laragon\www\lms\apps\lms-crm\app\(protected)\gestion-academique\admissions\candidats\components\details"
ren "collaborateur-access-details.tsx" "candidat-access-details.tsx"
ren "collaborateur-access-stats.tsx" "candidat-access-stats.tsx"
ren "collaborateur-hr-info.tsx" "candidat-info.tsx"
ren "collaborateur-overview-stats.tsx" "candidat-overview-stats.tsx"
ren "collaborateur-permissions-list.tsx" "candidat-permissions-list.tsx"
ren "collaborateur-recent-activity.tsx" "candidat-recent-activity.tsx"
ren "collaborateur-reliability-tier.tsx" "candidat-reliability-tier.tsx"
ren "collaborateur-roles-groups.tsx" "candidat-roles-groups.tsx"
